Feature/ordenation
vtex-apps/badges pull request #13
Opened 2021-09-28 17:11 UTC by anamaiabap

Arrumando ultimos ajustes para a liberação do beta

2021-09-28 18:04 UTC, wagnerlduarte requested changes

2021-09-28 18:04 UTC, wagnerlduarte commented on react/utils/conditionsProps.tsx
> +function getWhere(props: any) {
It's a good practice add a type on parameters. I suggest add type on `props`. 📝

2021-09-29 13:28 UTC, anamaiabap commented on react/utils/conditionsProps.tsx
> +function getWhere(props: any) {
Meu problema é que ele vem com os valores de retorno do store, então eu não tenho controle do que pode vir...

2021-09-29 19:43 UTC, wagnerlduarte approved these changes

2021-09-29 19:43 UTC, merged