Feature/regra ativação simplificada
vtex-apps/badges pull request #2
Opened 2021-07-20 12:24 UTC by anamaiabap

1. Pegando os valores validos para os campos de Produto, Sku, Categoria, Marca, Coleção, Especificação
2. Criando as queries para o 1.
3. Todos os campos de preenchimento de regra de ativação devem ser input
4. Criando o botão de salvar as modificações

2021-07-20 14:09 UTC, gabrielHosino commented on node/clients/product.ts
> +    }
I think you can do something similar to what i suggested on getProductsNames

2021-07-20 14:09 UTC, gabrielHosino commented on node/clients/sku.ts
> +    }
Here too 😄

2021-07-20 14:09 UTC, gabrielHosino commented on react/Provider/provider.tsx
> +  }
Is this a TODO?

2021-07-20 14:09 UTC, gabrielHosino commented on react/utils/functionsConditions.tsx
> +} */
Will this be used later?

2021-07-20 16:59 UTC, brunorodmoreira requested changes
@anamaiabap I think you should remove that unused structured before submit to merging. You can use the [stash](https://medium.com/wooza/git-stash-conhecendo-e-utilizando-um-dos-comandos-mais-pr%C3%A1ticos-para-o-versionamento-de-seu-c%C3%B3digo-a4dab3ac70da) commando from git

2021-07-20 16:59 UTC, brunorodmoreira commented on admin/routes.json
>      "path": "/admin/app/badges"
it would be good to change these boilerplate names already

2021-07-20 16:59 UTC, brunorodmoreira commented on graphql/schema.graphql
> +}
it would also be good to remove this query if it's not being currently used.

2021-07-20 16:59 UTC, brunorodmoreira commented on manifest.json
> +    "node": "6.x"
Same as before, removing unused builders.

```suggestion
    "docs": "0.x"
```

2021-07-20 16:59 UTC, brunorodmoreira commented on manifest.json
> +  ]
Removing unnecessary policies.

```suggestion
  "$schema": "https://raw.githubusercontent.com/vtex/node-vtex-api/master/gen/manifest.schema"
```

2021-07-20 16:59 UTC, brunorodmoreira commented on messages/pt.json
> +  "badges.navigation.label": "Gerenciamento de Badges Novo",
It would be nice to commit with a proper message here or with a marked `TODO`

2021-07-21 16:44 UTC, anamaiabap commented on react/Provider/provider.tsx
> +  }
Exato, vai estar no proximo PR :)

2021-07-22 17:27 UTC, merged