Feature/save
vtex-apps/badges pull request #3
Opened 2021-07-22 17:32 UTC by anamaiabap

1. Validando se todos os campos foram preenchidos e colocando um texto na tela caso não foram
2. Salvando em uma variável todos os valores dos campos preenchidos

2021-07-23 19:13 UTC, ConradoClark commented on react/Provider/provider.tsx
> +  }
This is just a suggestion

But I think that instead of using those conditionals, you could have separate objects to represent those different kinds of buttons, something like this:

```typescript
enum ButtonOptions {
  Image,
  Text,
  Html
}

interface ButtonOption {
  type: 'image' | 'text' | 'html'
  value?: string
  validate: (content: string) => string[]
}

// this could be declared inside another file
const imageButtonOption = {
  type: 'image',
  validate: (content) => !content ? ['Adicione uma imagem no campo "Tipo de badge"'] : []
}
// ... you could do the same with textButtonOption and htmlButtonOption

// Declare buttonOptions like this
const buttonOptions: {
    [key in ButtonOptions]: ButtonOption
} = useMemo( () => {
  [ButtonOptions.Image]: { ...imageButtonOption, value: file?.result },
  [ButtonOptions.Text]: { ...textButtonOption, value: text },
  [ButtonOptions.Html]: { ...htmlButtonOption, value: html }
}, [file, text, html])

// and use it like this
const option = buttonOptions[button] // you could change button type from int to the recently created enum
valueSave.type = option.type
valueSave.typeValue = option.value
```

2021-07-23 19:13 UTC, ConradoClark commented on react/Provider/provider.tsx
> +    if (button === 1 && (file.result === null || file.result === undefined)) {
The other comment I posted about changing the way you deal with these "if" conditions for the button prop could help here too. you could simply use: `buttonOptions[button].validate()` instead of testing which kind of button you're using, and push the results to the validation array.

2021-07-23 19:13 UTC, ConradoClark commented on react/Context/context.tsx
> +    simpleStatements: never[]
Maybe `never[]` here should be changed as well.

2021-07-23 19:13 UTC, ConradoClark commented on react/Context/context.tsx
> +    simpleStatements: never[]
I just noticed I made the comments from bottom to top 🙄  (so the explanation for this is at the bottom)

2021-07-27 11:47 UTC, wagnerlduarte commented on react/Components/input.tsx
> +  if (name === 'name') {
Why the `useCallback` was removed here?

2021-07-27 11:47 UTC, wagnerlduarte commented on react/utils/functionsConditions.tsx
> +      onChange={(e: { target: { value: any } }) => {
Here I think that you can change generic type to `React.ChangeEvent<HTMLInputElement>`

```suggestion
      onChange={(e: React.ChangeEvent<HTMLInputElement>) => {
```

2021-07-28 11:49 UTC, anamaiabap commented on react/Components/input.tsx
> +  if (name === 'name') {
Foi removido porque com o useCallback não estava conseguindo atualizar os valores do useState, parecia que estava impedindo a mudança dos valores

2021-07-28 11:49 UTC, anamaiabap commented on react/Provider/provider.tsx
> +  }
Não sei se entendi bem, mas irei te chamar no privado para a gente discutir melhor :)

2021-07-28 18:03 UTC, wagnerlduarte commented on react/Components/input.tsx
> +  if (name === 'name') {
Yeah, it's happens because you need to add the variables inside your function at the array of observables. I recomend that you configure the `eslint` for it alert you with what you need to add to `useCallback` work good. Usually the `react-hooks/exhaustive-deps` suggesti you in this case.

Would you try it and call me if you need any help, right?

2021-08-05 13:17 UTC, wagnerlduarte commented on node/clients/product.ts
> +    const names: Array<{ id: string; name: string }> = []
I suggest create a interface to use in this and other cases that use the same structure, you know?

```suggestion
    interface Name {
         id: string
         name: string
    }
    ...
    const names: Array<Name> = []
```

or

```suggestion
    interface Name {
         id: string
         name: string
    }
    ...
    const names: Name[] = []
```

2021-08-05 15:02 UTC, wagnerlduarte requested changes

2021-08-05 15:02 UTC, wagnerlduarte commented on react/utils/autoComplete.tsx
> +  if (name === 'specificationProperties') values = provider.nameSpecification
It's a better idea use dictionary in this case, to avoid multiples `if` checks

```suggestion
  enum fieldNames {
    productId,
    selectedItemId,
    brandId,
    productClusters,
    categoryId,
    specificationProperties,
  }

 ...

  const fields: { [key in keyof typeof fieldNames]: string } = useMemo(() => {
    return {
      productId: provider.nameProducts,
      selectedItemId: provider.nameSku,
      brandId: provider.nameBrands,
      productClusters: provider.nameCollections,
      categoryId: provider.nameCategory,
      specificationProperties: provider.nameSpecification,
    }
  }, [
    provider.nameBrands,
    provider.nameCategory,
    provider.nameCollections,
    provider.nameProducts,
    provider.nameSku,
    provider.nameSpecification,
  ])

  const values = useMemo(() => fields[name], [fields, name])
```

2021-08-11 13:04 UTC, wagnerlduarte commented on node/clients/product.ts
> +    value.forEach((element: { id: string; name: string }) => {
You can use the type `Name` here too

2021-08-11 13:04 UTC, wagnerlduarte commented on node/clients/product.ts
> +    items.forEach((element: { id: string; name: string }) => {
You can use the type `Name` here too

2021-08-11 13:14 UTC, wagnerlduarte commented on react/Provider/provider.tsx
> +    if (name === null || name === undefined || name === '') {
```suggestion
    if (!name) {
```

2021-08-11 17:28 UTC, merged