Feature/masterdata v2
vtex-apps/badges pull request #4
Opened 2021-07-26 18:58 UTC by anamaiabap

1. Salvando a imagem em um banco de dados e resgatando a url
2. Salvando os dados das badges no masterdata v2
3. Adicionando alerta se os dados foram salvos ou não

2021-07-27 12:52 UTC, felipefadul requested changes
It seems good! Just a few suggestions to improve some points.

2021-07-27 12:52 UTC, felipefadul commented on react/Provider/provider.tsx
> +    if (name === null || name === undefined || name === '') {
You can do this here:

```suggestion
    if (!name) {
```

2021-07-27 12:52 UTC, felipefadul commented on react/Provider/provider.tsx
> +    if (name === null || name === undefined || name === '') {
Similar [here](https://github.com/vtex-apps/badges/pull/4/files#diff-1d25edb2b7119b3ab49f6e24d11a2a123b475183c2f82435efda2bf7fb1f225dR46) and [here](https://github.com/vtex-apps/badges/pull/4/files#diff-1d25edb2b7119b3ab49f6e24d11a2a123b475183c2f82435efda2bf7fb1f225dR50).

2021-07-27 12:52 UTC, felipefadul commented on react/Components/alert.tsx
> +  }
What do you think about extracting numbers '1' and '2' to global constants? I think it will help on code maintenance and improve readability by avoiding some 'magic numbers', rsrs.

2021-07-27 12:52 UTC, felipefadul commented on react/Provider/provider.tsx
> +      }
I would extract the numbers '1', '2' and '3' here also for constants (global if used anywhere else). What do you think?

2021-07-27 13:06 UTC, wagnerlduarte requested changes
Do you really want to open this pull request to `release/0.0.1`?
To me it looks like you wanted to open to `feature/save`, right?

2021-07-27 13:22 UTC, felipefadul commented
> 
> 
> Do you really want to open this pull request to `release/0.0.1`?
> To me it looks like you wanted to open to `feature/save`, right?

Its true! There are comments on [PR3](https://github.com/vtex-apps/badges/pull/3) that point some things I have pointed (just saw now) and their suggestions are better than mine, haha.

2021-07-28 17:59 UTC, felipefadul requested changes

2021-07-28 17:59 UTC, felipefadul commented on react/Provider/provider.tsx
>    const [button, setButton] = useState(1)
Just missing here :)

```suggestion
  const [button, setButton] = useState(BUTTON_CHOICE_IS_IMAGEM)
```

2021-07-28 18:21 UTC, wagnerlduarte requested changes

2021-07-28 18:21 UTC, wagnerlduarte commented on react/Provider/provider.tsx
> +      setShowAlert(1)
What is `0` `1` `2` that you set with this state? A better solution is convert this values as `const` or `enum`

2021-07-28 18:21 UTC, wagnerlduarte commented on react/Provider/provider.tsx
>    const [button, setButton] = useState(1)
I believe this [suggestion ](https://github.com/vtex-apps/badges/pull/3#discussion_r675807551) is a better solution in this case 😄

2021-07-28 18:21 UTC, wagnerlduarte commented on node/resolvers/saveMasterdata.ts
> +  }
Just a suggestion and a curiosity to. You can use destructuring to improve your code here, to avoid use repetitive objects.

Example:

```suggestion

  const { name, content, operator, simpleStatements, type } = saveValues.saveData

  if (name.length === 0) {
    throw new Error('É necessário enviar um name')
  }

  if (content.length === 0) {
    throw new Error('É necessário enviar um content')
  }

  if (operator.length === 0) {
    throw new Error('É necessário enviar um operator')
  }

  if (simpleStatements.length === 0) {
    throw new Error('É necessário enviar um simpleStatements')
  }

  if (type.length === 0) {
    throw new Error('É necessário enviar um type')
  }
```

2021-07-28 18:21 UTC, wagnerlduarte commented on react/Components/alert.tsx
> +  }
This [suggestion](https://github.com/vtex-apps/badges/pull/3#discussion_r675807551) can be used here 😄

2021-08-05 21:40 UTC, felipefadul requested changes

2021-08-05 21:40 UTC, felipefadul commented on react/Provider/provider.tsx
> +const SHOW_ALERT_ERROR = 2
Just a suggestion to improve even more:

```suggestion
const enum ButtonOptions = {
  image = 1,
  text = 2,
  html = 3,
}

const enum ShowAlertOptions = {
  notShow = 0,
  alertSave = 1,
  alertError = 2,
}
```

But as it is used in different files ([here](https://github.com/vtex-apps/badges/pull/4/files#diff-a63028146fdca5102f21f66d2f75af7b609fe825c7e21fa1c035c3f4b21a9424R36) and [here](https://github.com/vtex-apps/badges/pull/4/files#diff-a63028146fdca5102f21f66d2f75af7b609fe825c7e21fa1c035c3f4b21a9424R51), for example), these `enums`can be declared as global types. See this declaration example [here](https://github.com/vtex/support-center-admin/blob/fix%2Fsatisfaction-bug/react/typings/enums/satisfactionQuestionAnswers.ts) and using it [here](https://github.com/vtex/support-center-admin/blob/fix%2Fsatisfaction-bug/react/components/questions/ThumbIcons.tsx), please. What do you think?

2021-08-11 13:19 UTC, wagnerlduarte approved these changes

2021-08-11 17:56 UTC, felipefadul approved these changes
LGTM!

2021-08-11 18:00 UTC, merged