Feature/edit admin
vtex-apps/badges pull request #7
Opened 2021-08-17 17:02 UTC by anamaiabap

Criando a parte de edição das badges já cadastradas
Se quiserem testar na prática, podem acessar : https://ana--sandboxbrdev.myvtex.com/admin/badges na aba de edição

2021-08-18 12:11 UTC, wagnerlduarte requested changes

2021-08-18 12:11 UTC, wagnerlduarte commented on react/Provider/provider.tsx
> +    if (valuesSearchBadges[index].type === 'html') {
Do you have a enum or type that represents `html` and `text`, no? Try to use them in this cases. It's a better practice than literal `string`.

2021-08-18 12:11 UTC, wagnerlduarte commented on react/Provider/provider.tsx
> +      }
Change alert to `Toasty` here too.

2021-08-18 12:11 UTC, wagnerlduarte commented on react/Components/modalEdit.tsx
> +    if (button === 'text') return <InputArea name={'text'} />
Use `enum` or `type` in these case. Using a literal `string` isn't a better way to maintain the code in the future.

2021-08-18 12:11 UTC, wagnerlduarte commented on node/resolvers/deleteMasterdata.ts
> +        `Erro ao deletar Badge através do MasterdataV2 ${e}`
Translate to english this message

2021-08-18 12:11 UTC, wagnerlduarte commented on node/resolvers/updateMasterdata.ts
> +  }
Translate to english these messages

2021-08-18 20:10 UTC, anamaiabap commented on react/Provider/provider.tsx
> +    }
Amei a dica!!

2021-08-20 14:10 UTC, wagnerlduarte approved these changes

2021-08-24 17:15 UTC, wagnerlduarte approved these changes

2021-08-24 17:16 UTC, merged